<?php
/**
 * Plugin Name: Luvron — GST E-Invoice (IRN/QR)
 * Description: Generates IRN and QR code for B2B invoices via the IRP (Invoice Registration Portal).
 *              Supports two modes:
 *                1. Manual — admin enters IRN/QR after generating from external tool (zero-cost)
 *                2. API — auto-generate via ClearTax/Cygnet/GSTHero IRP API (₹15-25k/yr)
 *              Mandatory under GST law if turnover ≥ ₹5 cr.
 * Version: 1.0.0
 */

if (!defined('ABSPATH')) exit;
if (function_exists('luvron_disabled') && luvron_disabled('luvron-einvoice')) return;

const LUVRON_EI_OPT = 'luvron_einvoice';

add_action('admin_menu', function () {
    add_options_page('Luvron E-Invoice', 'Luvron E-Invoice', 'manage_options',
        'luvron-einvoice', 'luvron_einvoice_settings');
});

add_action('admin_init', function () {
    register_setting('luvron_ei_group', LUVRON_EI_OPT, [
        'sanitize_callback' => function ($v) {
            return [
                'enabled'    => !empty($v['enabled']) ? 1 : 0,
                'mode'       => in_array($v['mode'] ?? '', ['manual','api'], true) ? $v['mode'] : 'manual',
                'provider'   => in_array($v['provider'] ?? '', ['cleartax','cygnet','gsthero'], true) ? $v['provider'] : 'cleartax',
                'api_endpoint' => esc_url_raw($v['api_endpoint'] ?? ''),
                'api_user'   => sanitize_text_field($v['api_user'] ?? ''),
                'api_secret' => sanitize_text_field($v['api_secret'] ?? ''),
                'gstin'      => sanitize_text_field($v['gstin'] ?? '09XXXXXXXXXXX1Z5'),
                'turnover_threshold' => (float) ($v['turnover_threshold'] ?? 50000000), // ₹5 cr
            ];
        },
    ]);
});

function luvron_einvoice_settings() {
    $o = get_option(LUVRON_EI_OPT, []);
    ?>
    <div class="wrap">
        <h1>Luvron GST E-Invoice (IRN/QR)</h1>
        <p>If Luvron's annual turnover ≥ ₹5 crore, GST e-invoicing is <strong>mandatory</strong>. Every B2B tax invoice must carry an IRN and QR code generated by the government IRP, or your buyer cannot claim input credit and you face ₹10,000/invoice penalty.</p>

        <form method="post" action="options.php">
            <?php settings_fields('luvron_ei_group'); ?>
            <table class="form-table">
                <tr><th>Enable</th><td><label><input type="checkbox" name="<?php echo LUVRON_EI_OPT; ?>[enabled]" value="1" <?php checked(!empty($o['enabled'])); ?>> Enable e-invoice generation on tax invoices</label></td></tr>
                <tr><th>Mode</th><td>
                    <label><input type="radio" name="<?php echo LUVRON_EI_OPT; ?>[mode]" value="manual" <?php checked(($o['mode'] ?? 'manual'),'manual'); ?>> <strong>Manual</strong> (free) — admin pastes IRN/QR from external tool per invoice</label><br>
                    <label><input type="radio" name="<?php echo LUVRON_EI_OPT; ?>[mode]" value="api" <?php checked(($o['mode'] ?? 'manual'),'api'); ?>> <strong>API</strong> — auto-generate via IRP provider</label>
                </td></tr>
                <tr><th>API Provider</th><td>
                    <select name="<?php echo LUVRON_EI_OPT; ?>[provider]">
                        <option value="cleartax" <?php selected(($o['provider']??''),'cleartax'); ?>>ClearTax</option>
                        <option value="cygnet"   <?php selected(($o['provider']??''),'cygnet');   ?>>Cygnet</option>
                        <option value="gsthero"  <?php selected(($o['provider']??''),'gsthero');  ?>>GSTHero</option>
                    </select>
                </td></tr>
                <tr><th>API Endpoint</th><td><input type="url" class="regular-text" name="<?php echo LUVRON_EI_OPT; ?>[api_endpoint]" value="<?php echo esc_attr($o['api_endpoint'] ?? ''); ?>" placeholder="https://einv-apisandbox.nic.in/eivital/dec/v1.04/auth"></td></tr>
                <tr><th>API User</th><td><input type="text" class="regular-text" name="<?php echo LUVRON_EI_OPT; ?>[api_user]" value="<?php echo esc_attr($o['api_user'] ?? ''); ?>"></td></tr>
                <tr><th>API Secret</th><td><input type="password" class="regular-text" name="<?php echo LUVRON_EI_OPT; ?>[api_secret]" value="<?php echo esc_attr($o['api_secret'] ?? ''); ?>"></td></tr>
                <tr><th>Seller GSTIN</th><td><input type="text" class="regular-text" name="<?php echo LUVRON_EI_OPT; ?>[gstin]" value="<?php echo esc_attr($o['gstin'] ?? ''); ?>"></td></tr>
            </table>
            <?php submit_button(); ?>
        </form>
    </div>
    <?php
}

function luvron_einvoice_payload($order) {
    $o = get_option(LUVRON_EI_OPT, []);
    $items = [];
    foreach ($order->get_items() as $i => $item) {
        $product = $item->get_product();
        if (!$product) continue;
        $hsn = get_post_meta($product->get_id(), '_hsn_code', true) ?: '95030010';
        $rate = (float) (get_post_meta($product->get_id(), '_gst_rate', true) ?: 18);
        $taxable = (float) $item->get_subtotal();
        $tax     = (float) $item->get_total_tax();
        $items[] = [
            'SlNo'       => (string) ($i + 1),
            'PrdDesc'    => $item->get_name(),
            'IsServc'    => 'N',
            'HsnCd'      => $hsn,
            'Qty'        => (float) $item->get_quantity(),
            'Unit'       => 'NOS',
            'UnitPrice'  => round($taxable / max($item->get_quantity(),1), 2),
            'TotAmt'     => round($taxable, 2),
            'AssAmt'     => round($taxable, 2),
            'GstRt'      => $rate,
            'IgstAmt'    => $order->get_billing_state() !== 'UP' ? round($tax, 2) : 0,
            'CgstAmt'    => $order->get_billing_state() === 'UP' ? round($tax/2, 2) : 0,
            'SgstAmt'    => $order->get_billing_state() === 'UP' ? round($tax/2, 2) : 0,
            'TotItemVal' => round($taxable + $tax, 2),
        ];
    }
    return [
        'Version'     => '1.1',
        'TranDtls'    => ['TaxSch' => 'GST', 'SupTyp' => 'B2B', 'IgstOnIntra' => 'N'],
        'DocDtls'     => [
            'Typ'  => 'INV',
            'No'   => 'LUV/' . date('Y') . '/' . str_pad($order->get_id(), 5, '0', STR_PAD_LEFT),
            'Dt'   => $order->get_date_created()->format('d/m/Y'),
        ],
        'SellerDtls'  => [
            'Gstin' => $o['gstin'] ?? '09XXXXXXXXXXX1Z5',
            'LglNm' => 'Luvron Tricycles',
            'Addr1' => 'OFF-D-337, T-04, Indraprastha Colony',
            'Loc'   => 'Loni, Ghaziabad',
            'Pin'   => 201102,
            'Stcd'  => '09',
        ],
        'BuyerDtls'   => [
            'Gstin' => $order->get_meta('_billing_gstin') ?: 'URP',
            'LglNm' => $order->get_billing_company() ?: $order->get_formatted_billing_full_name(),
            'Pos'   => luvron_state_to_code($order->get_billing_state()),
            'Addr1' => $order->get_billing_address_1(),
            'Loc'   => $order->get_billing_city(),
            'Pin'   => (int) $order->get_billing_postcode() ?: 110001,
            'Stcd'  => luvron_state_to_code($order->get_billing_state()),
        ],
        'ItemList'    => $items,
        'ValDtls'     => [
            'AssVal'   => round($order->get_subtotal(), 2),
            'IgstVal'  => $order->get_billing_state() !== 'UP' ? round($order->get_total_tax(), 2) : 0,
            'CgstVal'  => $order->get_billing_state() === 'UP' ? round($order->get_total_tax()/2, 2) : 0,
            'SgstVal'  => $order->get_billing_state() === 'UP' ? round($order->get_total_tax()/2, 2) : 0,
            'TotInvVal' => round($order->get_total(), 2),
        ],
    ];
}

function luvron_state_to_code($state) {
    $map = ['UP'=>'09','DL'=>'07','HR'=>'06','MH'=>'27','KA'=>'29','TN'=>'33',
            'GJ'=>'24','RJ'=>'08','WB'=>'19','AP'=>'37','TS'=>'36','PB'=>'03',
            'KL'=>'32','MP'=>'23','OR'=>'21','BR'=>'10','JH'=>'20','CT'=>'22',
            'AS'=>'18','HP'=>'02','UT'=>'05','GA'=>'30','TR'=>'16','MN'=>'14',
            'ML'=>'17','AR'=>'12','MZ'=>'15','NL'=>'13','SK'=>'11','JK'=>'01',
            'LA'=>'38','AN'=>'35','CH'=>'04','DN'=>'26','LD'=>'31','PY'=>'34'];
    return $map[$state] ?? '00';
}

function luvron_einvoice_generate_via_api($order) {
    $o = get_option(LUVRON_EI_OPT, []);
    if (empty($o['api_endpoint']) || empty($o['api_user'])) {
        return new WP_Error('config', 'API not configured');
    }
    $payload = luvron_einvoice_payload($order);
    $res = wp_remote_post($o['api_endpoint'], [
        'timeout' => 20,
        'headers' => [
            'Content-Type' => 'application/json',
            'Authorization' => 'Bearer ' . $o['api_secret'],
            'X-User'  => $o['api_user'],
            'X-Provider' => $o['provider'],
        ],
        'body' => wp_json_encode($payload),
    ]);
    if (is_wp_error($res)) return $res;
    $body = json_decode(wp_remote_retrieve_body($res), true);
    if (!empty($body['Irn']) || !empty($body['IRN'])) {
        $irn = $body['Irn'] ?? $body['IRN'];
        $qr  = $body['SignedQRCode'] ?? $body['QRCode'] ?? '';
        $ack = $body['AckNo'] ?? '';
        $ack_dt = $body['AckDt'] ?? '';
        $order->update_meta_data('_luvron_irn', $irn);
        $order->update_meta_data('_luvron_irn_qr', $qr);
        $order->update_meta_data('_luvron_irn_ack', $ack);
        $order->update_meta_data('_luvron_irn_dt', $ack_dt);
        $order->save();
        return ['irn' => $irn, 'qr' => $qr];
    }
    return new WP_Error('irp_fail', $body['error'] ?? 'IRP rejected');
}

add_action('woocommerce_order_actions', function ($actions) {
    $actions['luvron_generate_irn'] = 'Generate IRN/QR (E-Invoice)';
    return $actions;
});

add_action('woocommerce_order_action_luvron_generate_irn', function ($order) {
    $o = get_option(LUVRON_EI_OPT, []);
    if (empty($o['enabled'])) {
        $order->add_order_note('E-invoice generation requested but module disabled');
        return;
    }
    if ($o['mode'] === 'api') {
        $r = luvron_einvoice_generate_via_api($order);
        if (is_wp_error($r)) {
            $order->add_order_note('IRN API failed: ' . $r->get_error_message());
        } else {
            $order->add_order_note('IRN generated: ' . $r['irn']);
            $order->update_status('processing');
        }
    } else {
        $order->add_order_note('Manual IRN mode — please paste IRN/QR in custom fields');
    }
});

add_action('add_meta_boxes', function () {
    add_meta_box('luvron_irn_box', 'GST E-Invoice (IRN/QR)', 'luvron_irn_metabox',
        ['shop_order', 'woocommerce_page_wc-orders'], 'side', 'high');
});

function luvron_irn_metabox($post_or_order) {
    $order = $post_or_order instanceof WP_Post ? wc_get_order($post_or_order->ID) : $post_or_order;
    if (!$order) return;
    wp_nonce_field('luvron_irn_save', 'luvron_irn_nonce');
    $irn = $order->get_meta('_luvron_irn');
    $qr  = $order->get_meta('_luvron_irn_qr');
    ?>
    <p><label>IRN (64-char)<br>
        <input type="text" name="_luvron_irn" value="<?php echo esc_attr($irn); ?>" style="width:100%;font-family:monospace;font-size:11px;"></label></p>
    <p><label>Signed QR Code (base64)<br>
        <textarea name="_luvron_irn_qr" rows="4" style="width:100%;font-family:monospace;font-size:10px;"><?php echo esc_textarea($qr); ?></textarea></label></p>
    <?php if ($qr): ?>
        <p><strong>QR will appear on the invoice PDF.</strong></p>
    <?php endif;
}

add_action('woocommerce_process_shop_order_meta', function ($order_id, $post = null) {
    if (empty($_POST['luvron_irn_nonce']) || !wp_verify_nonce($_POST['luvron_irn_nonce'], 'luvron_irn_save')) return;
    $order = wc_get_order($order_id);
    if (!$order) return;
    $order->update_meta_data('_luvron_irn', sanitize_text_field($_POST['_luvron_irn'] ?? ''));
    $order->update_meta_data('_luvron_irn_qr', sanitize_textarea_field($_POST['_luvron_irn_qr'] ?? ''));
    $order->save();
}, 10, 2);
